### ISSUE TITLE
Error when initializing ESLint

### ISSUE THREAD

**Issue by iamkd** [zalishchuk/eslint-config-zalishchuk#1]
```
/node_modules/eslint-config-zalishchuk/index.js:
Configuration for rule "react/jsx-no-bind" is invalid: 	Value "[object Object]" should NOT have additional properties. 
```
Sasha pochini

**Comment by zalishchuk** [comment]
@iamkd Current `react/jsx-no-bind` [configuration](https://github.com/zalishchuk/eslint-config-zalishchuk/blob/master/rules/plugin-react.js#L128) is valid according to [rule docs](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md).
